// common
export const PAY_CONFIG_VISIBLE = 'PAY_CONFIG_VISIBLE'
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE'
// account recharge
export const RECEIVE_RECHARGE_BY_PAGE = 'RECEIVE_RECHARGE_BY_PAGE'
export const RECEIVE_RECHARGE_TOTAL = 'RECEIVE_RECHARGE_TOTAL'
// order management
export const RECEIVE_ORDER_BY_PAGE = 'RECEIVE_ORDER_BY_PAGE'
export const RECEIVE_ORDER_TOTAL = 'RECEIVE_ORDER_TOTAL'
export const INVOICE_CONFIG_VISIBLE = 'INVOICE_CONFIG_VISIBLE'
export const RECEIVE_ORDER_CODE = 'RECEIVE_ORDER_CODE'
export const RECEIVE_COUPON_CODE = 'RECEIVE_COUPON_CODE'
export const CHANGE_ORDER_LIST = 'CHANGE_ORDER_LIST'
// order pay
export const RECEIVE_PAY_PRICE = 'RECEIVE_PAY_PRICE'
export const RECEIVE_INSUFFICIENT = 'RECEIVE_INSUFFICIENT'
// invoice mangement
export const RECEIVE_INVOICE_BY_PAGE = 'RECEIVE_INVOICE_BY_PAGE'
export const RECEIVE_INVOICE_TOTAL = 'RECEIVE_INVOICE_TOTAL'
export const INVOICE_INFO_VISIBLE = 'INVOICE_INFO_VISIBLE'
export const RECEIVE_INVOICE_ID = 'RECEIVE_INVOICE_ID'
export const RECEIVE_INVOICE_STATUS = 'RECEIVE_INVOICE_STATUS'
export const RECEIVE_LIST_LOADED = 'RECEIVE_LIST_LOADED'
// coupon management
export const RECEIVE_COUPON_BY_PAGE = 'RECEIVE_COUPON_BY_PAGE'
export const RECEIVE_COUPON_TOTAL = 'RECEIVE_COUPON_TOTAL'
export const ALARM_CONFIG_VISIBLE = 'ALARM_CONFIG_VISIBLE'
export const TASK_CONFIG_VISIBLE = 'TASK_CONFIG_VISIBLE'
