// effect
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS'
// dialog
export const RECHARGE_VISIBLE = 'RECHARGE_VISIBLE'
// order
export const FETCH_COUPON_CODE = 'FETCH_COUPON_CODE'
export const FETCH_ORDER_CODE = 'FETCH_ORDER_CODE'
export const GET_ORDER_INFO = 'GET_ORDER_INFO'
export const GET_ORDER_PAY_PRICE = 'GET_ORDER_PAY_PRICE'
export const GET_ORDER_BALANCE = 'GET_ORDER_BALANCE'
export const GET_ORDER_INSUFFICIENT = 'GET_ORDER_INSUFFICIENT'
// taichi-ddos
export const GET_DOMAIN_LIST = 'GET_DOMAIN_LIST'
export const GET_TAICHI_MEAL_LIST = 'GET_TAICHIDDOS_MEAL_LIST'
export const GET_NODOMAIN_FROM_WEB = 'GET_NODOMAIN_FROM_WEB'
export const GET_TAICHI_SURPLUS_TIME = 'GET_TAICHI_SURPLUS_TIME'
export const CONFIRM_TAICHI_ORDER_INFO = 'CONFIRM_TAICHI_ORDER_INFO'
export const CONFIRM_TAICHI_TOTAL_PRICE = 'CONFIRM_TAICHI_TOTAL_PRICE'
export const GET_TAICHI_ORDER_CODE = 'GET_TAICHI_ORDER_CODE'
// taichi-dns
export const GET_TAICHI_DNS_DOMAIN_LIST = 'GET_TAICHI_DNS_DOMAIN_LIST'
export const GET_TAICHI_DNS_MEAL_LIST = 'GET_TAICHI_DNS_MEAL_LIST'
export const CONFIRM_TAICHI_DNS_ORDER_INFO = 'CONFIRM_TAICHI_DNS_ORDER_INFO'
export const CONFIRM_TAICHI_DNS_TOTAL_PRICE = 'CONFIRM_TAICHI_DNS_TOTAL_PRICE'
export const GET_TAICHI_DNS_ORDER_CODE = 'GET_TAICHI_DNS_ORDER_CODE'
// cloud-speed
export const GET_SPEED_SURPLUS_FLOW = 'GET_SPEED_SURPLUS_FLOW'
export const GET_SPEED_MEAL_LIST = 'GET_SPEED_MEAL_LIST'
export const CONFIRM_SPEED_ORDER_INFO = 'CONFIRM_SPEED_ORDER_INFO'
export const CONFIRM_SPEED_TOTAL_PRICE = 'CONFIRM_SPEED_TOTAL_PRICE'
export const GET_SPEED_ORDER_CODE = 'GET_SPEED_ORDER_CODE'
// cloud-resolving
export const GET_RESOLVING_MEAL_LIST = 'GET_RESOLVING_MEAL_LIST'
export const CONFIRM_RESOLVING_ORDER_INFO = 'CONFIRM_RESOLVING_ORDER_INFO'
export const CONFIRM_RESOLVING_TOTAL_PRICE = 'CONFIRM_RESOLVING_TOTAL_PRICE'
export const GET_RESOLVING_ORDER_CODE = 'GET_RESOLVING_ORDER_CODE'
// double-mirror
export const GET_DOUBLEMIRROR_MEAL_LIST = 'GET_DOUBLEMIRROR_MEAL_LIST'
export const GET_MIRROR_TOTAL_PRICE = 'GET_MIRROR_TOTAL_PRICE'
export const GET_MIRROR_ORDER_INFO = 'GET_MIRROR_ORDER_INFO'
export const GET_MIRROR_ORDER_CODE = 'GET_MIRROR_ORDER_CODE'
// message
export const GET_MESSAGE_MEAL_LIST = 'GET_MESSAGE_MEAL_LIST'
export const CONFIRM_MESSAGE_ORDER_INFO = 'CONFIRM_MESSAGE_ORDER_INFO'
export const CONFIRM_MESSAGE_TOTAL_PRICE = 'CONFIRM_MESSAGE_TOTAL_PRICE'
export const GET_MESSAGE_ORDER_CODE = 'GET_MESSAGE_ORDER_CODE'
// cloud-monitor
export const GET_MONITOR_MEAL_LIST = 'GET_MONITOR_MEAL_LIST'
export const CONFIRM_MONITOR_ORDER_INFO = 'CONFIRM_MONITOR_ORDER_INFO'
export const CONFIRM_MONITOR_TOTAL_PRICE = 'CONFIRM_MONITOR_TOTAL_PRICE'
export const GET_MONITOR_ORDER_CODE = 'GET_MONITOR_ORDER_CODE'
// shield-eye vulnerabilityScan & riskDetection
export const GET_SHIELD_MEAL_LIST = 'GET_SHIELD_MEAL_LIST'
export const CONFIRM_SHIELD_ORDER_INFO = 'CONFIRM_SHIELD_ORDER_INFO'
export const CONFIRM_SHIELD_TOTAL_PRICE = 'CONFIRM_SHIELD_TOTAL_PRICE'
export const GET_SHIELD_ORDER_CODE = 'GET_SHIELD_ORDER_CODE'
// red-guard
export const GET_REDGUARD_DOMAIN_LIST = 'GET_REDGUARD_DOMAIN_LIST'
export const GET_REDGUARD_MEAL_LIST = 'GET_REDGUARD_MEAL_LIST'
export const CONFIRM_REDGUARD_TOTAL_PRICE = 'CONFIRM_REDGUARD_TOTAL_PRICE'
export const CONFIRM_REDGUARD_ORDER_INFO = 'CONFIRM_REDGUARD_ORDER_INFO'
export const GET_REDGUARD_ORDER_CODE = 'GET_REDGUARD_ORDER_CODE'
export const FETCH_NODOMAIN_BY_ERROR = 'FETCH_NODOMAIN_BY_ERROR'
