// UI
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS'
export const CHANGE_EDIT_STATUS = 'CHANGE_EDIT_STATUS'
// dialog
export const SSLCONFIG_VISIBLE = 'SSLCONFIG_VISIBLE'
// logic
export const RECEIVE_CERTIFICATE_BY_PAGE = 'RECEIVE_CERTIFICATE_BY_PAGE'
export const RECEIVE_CERTIFICATE_TOTAL = 'RECEIVE_CERTIFICATE_TOTAL'
export const FETCH_PAGESIZE = 'FETCH_PAGESIZE'
